### ISSUE TITLE
error in UnvlogIt#title on valid rutube url

### ISSUE THREAD

**Issue by Zloy** [mamuso/acts_as_unvlogable#11]
Hi mamuso,
I tried to parse random Rutube url from the main page http://rutube.ru/video/536e5c9548348e7ee9cdfcc5e1f149ea/ and got an error. Does Rutube respond with invalid XML?

	Loading development environment (Rails 3.2.8)
	1.9.3p194 :001 > aha = UnvlogIt.new 'http://rutube.ru/video/536e5c9548348e7ee9cdfcc5e1f149ea/'
	 => #<UnvlogIt:0xbb8d4e4 @object=#<VgRutube:0xbb8ce68 @url="http://rutube.ru/video/536e5c9548348e7ee9cdfcc5e1f149ea/", @movie_id="536">> 
	1.9.3p194 :002 > aha.title
	REXML::ParseException: #<REXML::ParseException: Missing end tag for 'hr' (got "body")
	Line: 6
	Position: 175
	Last 80 unconsumed characters:
	>
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:335:in `pull_event'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:183:in `pull'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/rexml/parsers/treeparser.rb:22:in `parse'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/rexml/document.rb:231:in `build'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/rexml/document.rb:43:in `initialize'
	/usr/local/rvm/gems/ruby-1.9.3-p194/gems/xml-simple-1.1.2/lib/xmlsimple.rb:965:in `new'
	/usr/local/rvm/gems/ruby-1.9.3-p194/gems/xml-simple-1.1.2/lib/xmlsimple.rb:965:in `parse'
	/usr/local/rvm/gems/ruby-1.9.3-p194/gems/xml-simple-1.1.2/lib/xmlsimple.rb:164:in `xml_in'
	/usr/local/rvm/gems/ruby-1.9.3-p194/gems/xml-simple-1.1.2/lib/xmlsimple.rb:203:in `xml_in'
	/usr/local/rvm/gems/ruby-1.9.3-p194/gems/acts_as_unvlogable-1.0.0/lib/acts_as_unvlogable/vg_rutube.rb:69:in `rt_info'
	/usr/local/rvm/gems/ruby-1.9.3-p194/gems/acts_as_unvlogable-1.0.0/lib/acts_as_unvlogable/vg_rutube.rb:9:in `title'
	/usr/local/rvm/gems/ruby-1.9.3-p194/gems/acts_as_unvlogable-1.0.0/lib/acts_as_unvlogable.rb:33:in `title'
	(irb):2:in `irb_binding'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb/workspace.rb:80:in `eval'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb/workspace.rb:80:in `evaluate'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb/context.rb:254:in `evaluate'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb.rb:159:in `block (2 levels) in eval_input'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb.rb:273:in `signal_status'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb.rb:156:in `block in eval_input'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb/ruby-lex.rb:243:in `block (2 levels) in each_top_level_statement'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb/ruby-lex.rb:229:in `loop'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb/ruby-lex.rb:229:in `block in each_top_level_statement'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb/ruby-lex.rb:228:in `catch'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb/ruby-lex.rb:228:in `each_top_level_statement'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb.rb:155:in `eval_input'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb.rb:70:in `block in start'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb.rb:69:in `catch'
	/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb.rb:69:in `start'
	/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
	/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in `start'
	/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>'
	script/rails:6:in `require'
	script/rails:6:in `<main>'
	...
	Missing end tag for 'hr' (got "body")
	Line: 6
	Position: 175
	Last 80 unconsumed characters:

	Line: 6
	Position: 175
	Last 80 unconsumed characters:

		from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/rexml/parsers/treeparser.rb:95:in `rescue in parse'
		from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/rexml/parsers/treeparser.rb:20:in `parse'
		from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/rexml/document.rb:231:in `build'
		from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/rexml/document.rb:43:in `initialize'
		from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/xml-simple-1.1.2/lib/xmlsimple.rb:965:in `new'
		from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/xml-simple-1.1.2/lib/xmlsimple.rb:965:in `parse'
		from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/xml-simple-1.1.2/lib/xmlsimple.rb:164:in `xml_in'
		from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/xml-simple-1.1.2/lib/xmlsimple.rb:203:in `xml_in'
		from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/acts_as_unvlogable-1.0.0/lib/acts_as_unvlogable/vg_rutube.rb:69:in `rt_info'
		from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/acts_as_unvlogable-1.0.0/lib/acts_as_unvlogable/vg_rutube.rb:9:in `title'
		from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/acts_as_unvlogable-1.0.0/lib/acts_as_unvlogable.rb:33:in `title'
		from (irb):2
		from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
		from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in `start'
		from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>'
		from script/rails:6:in `require'
		from script/rails:6:in `<main>'1.9.3p194 :003 > aha.embed_url
	 => nil

**Comment by mamuso** [comment]
Cleaning issues, just published a new gem. This should be working now.
