### ISSUE TITLE
It is not working with vimo

### ISSUE THREAD

**Issue by ciserfan** [mamuso/acts_as_unvlogable#17]
Hello 

i have to used that for vimeo but when i am fetching imformation form vimo it is giving me error 

videotron = UnvlogIt.new("http://vimeo.com/79794849")
ArgumentError: Unsuported url or service
	from /home/cis/.rvm/gems/ruby-1.9.3-p374@linkmission/gems/acts_as_unvlogable-1.0.0/lib/acts_as_unvlogable.rb:26:in `initialize'
	from (irb):15:in `new'
	from (irb):15
	from /home/cis/.rvm/gems/ruby-1.9.3-p374@linkmission/gems/railties-3.1.12/lib/rails/commands/console.rb:45:in `start'
	from /home/cis/.rvm/gems/ruby-1.9.3-p374@linkmission/gems/railties-3.1.12/lib/rails/commands/console.rb:8:in `start'
	from /home/cis/.rvm/gems/ruby-1.9.3-p374@linkmission/gems/railties-3.1.12/lib/rails/commands.rb:40:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

**Comment by mamuso** [comment]
Cleaning issues, just published a new gem. This should be working now.
