### ISSUE TITLE
invalid gem: package metadata is missing

### ISSUE THREAD

**Issue by akeelahmedqureshi** [mamuso/acts_as_unvlogable#18]
Hello, 

when I am trying to install acts_as_unvlogable gem I got  the below error 
invalid gem: package metadata is missing in /home/cis/.rvm/gems/ruby-2.1.1@linkmission_test/cache/youtube_it-2.1.1.gem

I am using ruby 2.1.1 version 
and rails 4.1

**Comment by mamuso** [comment]
Cleaning issues, just published a new gem. This should be working now.
