### ISSUE TITLE
Youtube not working as provider anymore

### ISSUE THREAD

**Issue by aitor** [mamuso/acts_as_unvlogable#20]
Just a small heads up: the youtube_it gem is not working anymore. 

Youtube finally switched off the V2 of their Data API on May 6th 2015 ([source](http://youtube-eng.blogspot.com/2015/04/bye-bye-youtube-data-api-v2.html)). The gem's author seems to be unresponsive to the new situation (kylejginavan/youtube_it#251) so, right now, this gem seems to be a dead end. 

As mentioned in the previous link, some people is migrating to http://github.com/Fullscreen/yt. They support v3 and have a migration document: https://github.com/Fullscreen/yt/blob/master/YOUTUBE_IT.md. Unfortunately this gem requires ruby '>= 1.9.3' so if you switch to it, this new interpreter requirement should be stated in the acts_as_unvlogable gemspec.

**Comment by mamuso** [comment]
Thank you Aitor! I'm working on fixing it now

**Comment by aitor** [comment]
Hi again,

To fix my own problem (old, legacy servers with ruby < 1.9.3, minimal dependencies, no need for access to authenticated videos/info) I hacked away [Videodrome](github.com/linkingpaths/videodrome) two days ago and replaced my local UnvlogIt's youtube implementation to use it instead of the youtube_it gem.  

This said, yt is probably a much better replacement for UnvlogIt since it aims to be a full-fledged ruby client for Youtube Data API and allows you o eventually add methods to access private Youtube's video information.

Enjoy the weekend!

**Comment by mamuso** [comment]
I'm actually doing something similar for unvlog.com (this poor guy is really old!). I'll check your implementation because we probably don't need the powerful features from yt for basic operations

**Comment by aitor** [comment]
It has been made in a rush and there is definitely space for improvement but it works (I'm running it in a few production sites). 

But feel to pull request or create issues if you find something or have any suggestions.

**Comment by mamuso** [comment]
I'll do!
